### PR TITLE
Resolve #52 and fixes.

### LINKED ISSUE #52: To output or not to output when there's no difference...
HTML Side by Side Diff, HTML Inline Diff and HTML Unified Diff will produce output string `No differences found.` It's hard-coded in the `HtmlArray` class.
@JBlond Let me know if, and into what, you want this to be changed.

_Originally posted by @DigiLive in https://github.com/JBlond/php-diff/issues/50#issuecomment-659659840_

### PR DESCRIPTION
**Pull request by DigiLive**
- HTML renderer Inline, SideBySide and Unified return false when
  there's nothing to render.
- Text renderer Context, InlineCli and Unified return false when
  there's nothing to render.
  Main renderer returns false when there's nothing to render.
- Text renderer InlineCli renders line-ending `\n` instead of
  `PHP_EOL`.
- Added missing docBlock content.
- Updated docBlock of the SubRenderer Interface.
- Added method Diff::isIdentical().
- Updated README.md to reflect Diff::isIdentical().

### CODE REVIEW

File: lib/jblond/Diff.php [hunk 1]
```diff
@@ -73,6 +73,10 @@ class Diff
      * @see Diff::setOptions()
      */
     private $options = [];
+    /**
```
Comment (JBlond) [inline lib/jblond/Diff.php:76]: Please add an empty line above.

File: lib/jblond/Diff.php [hunk 2]
```diff
@@ -221,6 +225,20 @@ public function getArrayRange(array $array, int $start = 0, $end = null): array
...
 
+    /**
+     * Get if the compared versions are identical or have differences.
+     *
+     * @return bool True when identical.
+     */
+    public function isIdentical(): bool
+    {
+        if ($this->getGroupedOpCodes() === null) {
+            $this->getGroupedOpCodes();
```
Comment (JBlond) [inline lib/jblond/Diff.php:236]: Why call it twice? In the if statement it is already called. Or do I miss something?

Comment (DigiLive) [reply lib/jblond/Diff.php:236]: Good catch... I think phpstorm was being to helpful on this one. 😅
